#apiVersion: v1
#kind: Namespace
#metadata:
#  name: openshift-etcd-backup
#  labels:
#    app: openshift-etcd-backup
#  annotations:
#    openshift.io/node-selector: ''
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: openshift-etcd-backup
  namespace: openshift-etcd-backup
  labels:
    app: openshift-etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: openshift-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: openshift-etcd-backup
  namespace: openshift-etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
  labels:
    app: openshift-etcd-backup
rules:
- apiGroups: [""] 
  resources: 
     - "nodes" 
  verbs: ["get", "list"]
- apiGroups: [""] 
  resources: 
     - "pods" 
     - "pods/log" 
  verbs: ["get", "list", "create", "delete", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-etcd-backup
  labels:
    app: openshift-etcd-backup
subjects:
  - kind: ServiceAccount
    name: openshift-etcd-backup
    namespace: openshift-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-etcd-backup
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: openshift-etcd-backup
  namespace: openshift-etcd-backup
  labels:
    app: openshift-etcd-backup
spec:
  schedule: "56 23 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: openshift-etcd-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-etcd-backup
        spec:
          containers:
            - name: backup
              image: "registry.redhat.io/openshift4/ose-cli:v4.10"
              command:
                - "/bin/bash"
                - "-c"
                - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} --  oc debug {} -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -ctime +"3" -delete'
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 600
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "openshift-etcd-backup"
          serviceAccount: "openshift-etcd-backup"
